### ISSUE TITLE
scalecast starter example won't import on mac

### ISSUE THREAD

**Issue by adataylor** [mikekeith52/scalecast#76]
I get the following issue when trying to run the minimal example from this repo, simply on the initial import statements:

(error from python with line numbers removed)
>     from scalecast.Forecaster import Forecaster
>     from lightgbm import LGBMRegressor
>     from .basic import Booster, Dataset, Sequence, register_logger
>     from .compat import PANDAS_INSTALLED, concat, dt_DataTable, pd_CategoricalDtype, pd_DataFrame, pd_Series
>     from dask.dataframe import DataFrame as dask_DataFrame
>     import dask.dataframe._pyarrow_compat
>     copyreg.dispatch_table[pd.arrays.ArrowStringArray] = reduce_arrowextensionarray
> AttributeError: module 'pandas.arrays' has no attribute 'ArrowStringArray'
> 

I've played with different pandas installation versions- any idea why this is remaining stuck?

> pip install --upgrade scalecast
runs fine and says nothing needs to be changed.

**Comment by adataylor** [comment]
I can't tell if it might be related to this in the changelog:

> "Suppressed future warnings on import because of a pandas warning caused from importing LightGBM. If LightGBM does not fix this issue with an update, we might need to pull it from the default list of sklearn estimators; users would still be able to use LightGBM by importing it manually."

**Comment by mikekeith52** [comment]
I am looking into this. Can I see your LightGBM and Pandas versions? Also, sometimes using `conda install lightgbm` on MAC can help several other issues I've seen with that library and its compatibility with scalecast. But maybe we should take it out of the list of dependencies.

**Comment by adataylor** [comment]
I think I got it working in a new Python 3.8 env, with:

- lightgbm                  4.0.0
- numpy                     1.24.4
- pandas                    1.5.3

grpcio and catboost sometimes got in loops installing; this seemed to unjam them so I'll leave this link here if someone else hits that issue:
https://stackoverflow.com/questions/66640705/how-can-i-install-grpcio-on-an-apple-m1-silicon-laptop
